@startuml
'https://plantuml.com/class-diagram

interface PlayerDao{
    + getAllPlayers():List<Player>
    + add(Player player):void
    + delete(int playerIndex):void
    + sort():void
    + showLeaderboard():void
}

PlayerDao <|.. PlayerDaoImpl
PlayerDao <.left. EndMenu
Player <-right- PlayerDaoImpl

class PlayerDaoImpl {
    - players: List<Player>
    + PlayerDaoImpl(int difficulty)
    + getAllPlayers():List<Player>
    + add(Player player):void
    + sort():void
    + delete(int playerIndex):void
    + showLeaderboard():void
    + {static} readCsv(String path):LinkedList<Player>
    + {static} writeCsv(List<Player> playerList, String filePath):void
}

class Player {
    - testUserName:String
    - score:int
    - time:String
    + Player(String testUserName, int score, String time)
    + getTestUserName():String
    + getScore():int
    + getTime():String
    + compareTo(Player player):int
}

class EndMenu {
    - playerDaoImpl:PlayerDao
    + EndMenu(int difficult)
    + showEndPanel(int difficult):void
    + showPopUps(int score, String time, int difficult):void
    - getPlayerData():String[][]
}

@enduml